### ISSUE TITLE
Investigate 6 months back - Name Filter limitations

### ISSUE THREAD

**Issue by Bievens** [Microsoft/CloudAppSecurityDocs#557]
Appears the name filters in investigate 6 months back we lost the option to select "Activity object only, Actor only, or Any role"?

Is there another way to perform this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9450b1a9-f22b-c5d7-6789-676c9f4afc1f
* Version Independent ID: 8ada75ef-7a51-07dc-f69d-a71451b69cf1
* Content: [Working with Defender for Cloud Apps activity filters and queries](https://docs.microsoft.com/en-us/defender-cloud-apps/activity-filters-queries#query-activities-six-months-back)
* Content Source: [CloudAppSecurityDocs/activity-filters-queries.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/activity-filters-queries.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.
